
[global-config]
# Options: alt, ctrl, logo/super, mod2, mod3
meta-key = "alt"

focus-follows-mouse = true

workspace-names = ["main", "2", "3", "4", "5", "6", "7", "8", "9"]
bind-workspaces-to-numbers = true

win-move-cursor-button = "left"
win-resize-cursor-button = "right"

border-width = 2  # pixels
active-border-colour = [1.0, 0.0, 0.7, 1.0]  # rgba
inactive-border-colour = [0.6, 0.6, 0.9, 1.0]  # rgba

gap-width = 0

clear-colour = [0.73, 0.73, 0.73, 1.0]

[background]
colour = "#ff0000"
image = "/home/sandy/sway_bg.jpg"
mode = "fill"

[xkb-config]
model = "pc104"
layout = "widecolemak"
variant = "widecolemak"
options = "ctrl:nocaps"

[bar]
command = "waybar"
update-signal-number = 1

[ipc]
workspaces-filename = "/home/sandy/.viv_workspace_state.txt"

[debug]
mark-views-by-shell = false
mark-active-output = false

### LAYOUTS ###
# Configure any number of layouts. Each workspace gets an independent copy of each layout.
# Run `vivarium -h` to get a list of available layouts.
# The following options are available for each layout:
# - name : The layout name to display in bar programs and logs, can be anything
#          Defaults to matching the `layout` option.
# - layout : The name of the Vivarium layout function to use.
#            Run `vivarium -h` to get a list of available layout names.
# - show-borders : If true, draw borders around windows. Defaults to true.
# - ignore-excluded-regions : If true, tile windows across the full workspace regardless of
#                             space reserved for bars, system tray etc.

[[layout]]
name = "Tall"
layout = "split"

[[layout]]
name = "Fullscreen"
layout = "fullscreen"

[[layout]]
name = "Fullscreen no borders"
layout = "fullscreen"
ignore-excluded-regions = true
show-borders = false

### KEYBINDS ###
# Configure any number of keybinds. The following options are available for each one:
# - modifiers : List of strings, not compulsory, defaults to ["meta"]
# - keysym : Keysym to bind to. The keysym is the value of the key as interpreted by your keyboard layout.
#            You may not bind to both keysym and keycode in the same binding.
# - keycode : Keycode to bind to. The keycode is the numerical identifier of the hardware key.
#             It always has the same value for a given physical key regardless of your keyboard layout.
# - action : Any Vivarium action.
#            Run `vivarium -h` to show documentation of all available actions, or see examples below
# - <action-arguments> : Arguments for the `action`, if applicable.
#                        See action documentation for available arguments.
#
# To find the keysym or keycode of a given key, use tools like `wev` or `xev`.

[[keybind]]
keysym = "Q"
action = "terminate"

[[keybind]]
keysym = "T"
action = "do_exec"
executable = "alacritty"

[[keybind]]
modifiers = ["meta", "shift"]
keysym = "Return"
action = "do_exec"
executable = "alacritty"

[[keybind]]
keysym = "l"
action = "increment_divide"
increment = 0.05

[[keybind]]
keysym = "h"
action = "increment_divide"
increment = -0.05

[[keybind]]
keysym = "j"
action = "next_window"

[[keybind]]
keysym = "k"
action = "prev_window"

[[keybind]]
keysym = "J"
action = "shift_active_window_down"

[[keybind]]
keysym = "K"
action = "shift_active_window_up"

[[keybind]]
keysym = "t"
action = "tile_window"

[[keybind]]
keysym = "e"
action = "right_output"

[[keybind]]
keysym = "q"
action = "left_output"

[[keybind]]
keysym = "space"
action = "next_layout"

[[keybind]]
keysym = "E"
action = "shift_active_window_to_right_output"

[[keybind]]
keysym = "Q"
action = "shift_active_window_to_left_output"

[[keybind]]
keysym = "C"
action = "close_window"

[[keybind]]
keysym = "o"
action = "do_exec"
executable = "bemenu-run"

[[keybind]]
keysym = "Return"
action = "make_window_main"

[[keybind]]
modifiers = []
keysym = "XF86AudioMute"
action = "do_shell"
command = "pactl set-sink-mute 0 toggle"

[[keybind]]
modifiers = []
keysym = "XF86AudioLowerVolume"
action = "do_shell"
command = "amixer -q sset Master 3%-"

[[keybind]]
modifiers = []
keysym = "XF86AudioRaiseVolume"
action = "do_shell"
command = "amixer -q sset Master 3%+"

### LIBINPUT CONFIG ###
# Create any number of libinput configurations

[[libinput-config]]
device-name = "Logitech USB Trackball"
scroll-method = "scroll-button"
scroll-button = "8"
middle-emulation = true
left-handed = false
natural-scroll = false

### OUTPUT CONFIG ###
# An output is a Vivarium backend surface: usually each of your monitors is one output.

[[output-config]]