name: Check compile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Build vivarium
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
            sudo apt-get install libwayland-dev libwayland-server0 wayland-protocols libxkbcommon-dev

      - name: Checkout vivarium
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
           python -m pip install --upgrade pip
           python -m pip install ninja
           python -m pip install meson

      - name: Build vivarium
        run: |
          meson build
          ninja -C build
